#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: sync-bootstrap
  namespace: sync
spec:
  serviceAccountName: sync-sa
  fetch:
  - inline:
      paths:
        #@yaml/text-templated-strings
        config/app.yaml: |
          #@ load("@ytt:data", "data")
          ---
          apiVersion: kappctrl.k14s.io/v1alpha1
          kind: App
          metadata:
            name: sync
            namespace: sync
          spec:
            serviceAccountName: sync-sa
            fetch:
              - git:
                  url: (@= data.values.git.url @)
                  ref: (@= data.values.git.ref @)
                  subPath: #@ "(@= data.values.git.sub_path+"/" @)" + data.values.clustername
            template:
              - ytt:
                  paths: 
                  - config
            deploy:
              - kapp: {}
  template:
    - ytt:
        valuesFrom:
        - secretRef:
            name: cluster-name
  deploy:
    - kapp: {}