---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: cluster-name
  namespace: vmware-system-tmc
spec:
  serviceAccountName: sync-agent
  inputResources:
  - name: stack-config
    ref:
      apiVersion: v1
      kind: ConfigMap
      name: stack-config
  template:
    stringData:
      clustername: $(.stack-config.data.cluster_name)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: cluster-name
  namespace: vmware-system-tmc
spec:
  toNamespaces:
  - sync
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: cluster-name
  namespace: sync
spec:
  fromNamespace: vmware-system-tmc